name: Generate RSS Feed

on:
  workflow_dispatch:

jobs:
  generate-rss:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.MY_SECRET_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install feedgenerator beautifulsoup4 requests # ここにrequests追加

    - name: Generate RSS feed
      run: python makeRSS_Ledge.ai.py

    - name: Commit and push feed.xml
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add feed.xml
        git commit -m "Update feed.xml"
        git push origin HEAD:${{ github.ref }}
