name: Generate RSS Feed

on:
  workflow_dispatch:

jobs:
  generate-rss:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8' # Pythonバージョンを3.8に設定

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install feedgenerator

    - name: Generate RSS feed
      run: python your_script_name.py # スクリプトの名前を適切に変更する

    - name: Upload RSS feed
      uses: actions/upload-artifact@v2
      with:
        name: feed
        path: feed.xml
