name: Run Schedule Scraper

on:
  workflow_dispatch: # これで手動実行ができるようになる
  schedule:
    # 日本時間（協定世界時+9時間）で9時から21時(協定世界時で0時から12時)までの偶数時、2時間ごとに実行
    - cron: '0 0,2,4,6,8,10,12 * * *' 

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.MY_SECRET_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip3 install -r requirements.txt

    - name: Install Pyppeteer dependencies
      run: |
        sudo apt-get install -y libx11-xcb1 libxrandr2 libasound2 libpangocairo-1.0-0 libatk1.0-0 libatk-bridge2.0-0 libgtk-3-0
      
    - name: Install Chromium
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser

    - name: Cache Chromium
      uses: actions/cache@v2
      with:
        path: ~/.local/share/pyppeteer/local-chromium/
        key: ${{ runner.os }}-chromium-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-chromium-

    - name: Debug Chromium Path
      run: |
        find ~/ -name "local-chromium" -type d
        which chromium-browser # パスを表示するコマンド

    - name: Run Pyppeteer Script
      run: python3 makeRSS_Ledge.ai.py
      timeout-minutes: 10

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git stash # 変更を一時的に退避させる
        git pull --rebase # リモートリポジトリの変更を取り込む
        git stash pop # 退避させた変更を戻す
        git add feed.xml
        git commit -m "Update schedule RSS feed" || exit 0 # 変更がない場合はエラーを無視
        git push
      shell: /usr/bin/bash -e {0}
      env:
        pythonLocation: /opt/hostedtoolcache/Python/3.11.4/x64
        LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.11.4/x64/lib


